name: agrobridge_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # State managment
  riverpod: ^3.0.3
  flutter_riverpod: ^3.0.3
  hooks_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  # Hooks
  flutter_hooks: ^0.21.3+1 

  # Fonts
  google_fonts: ^6.3.3

  # Svg
  flutter_svg: ^2.2.3

  # Routing
  auto_route: ^11.1.0

  # Screen
  flutter_screenutil: ^5.9.3
  carousel_slider: ^5.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  auto_route_generator: ^10.4.0
  riverpod_generator: ^3.0.3

  # Builder 
  lean_builder: ^0.1.6
  build_runner: ^2.10.4


flutter_gen:
  integrations:
    image: true
    flutter_svg: true


flutter:
  uses-material-design: true


  assets:
    - assets/icons/